services:
  postgres:
    image: postgres:18
    container_name: datatran2025
    restart: unless-stopped
    environment:
      POSTGRES_DB: sinistros_2025
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dan1920

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:

